# Simple development Dockerfile for Zig application
FROM debian:latest

RUN apt-get update
RUN apt-get install -y \
    nodejs \
    curl \
    npm 
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo install --locked watchexec-cli

# Install Zig
ARG ZIG_VERSION=0.15.2
RUN curl -L https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz -o zig.tar.xz && \
    tar -xf zig.tar.xz && \
    mv zig-x86_64-linux-${ZIG_VERSION} /usr/local/zig && \
    ln -s /usr/local/zig/zig /usr/local/bin/zig


WORKDIR /app

# Copy and build
COPY build.zig build.zig.zon ./
RUN zig build --fetch

COPY src/ ./src/
COPY crossword.map ./

# Build in debug mode for development

ENV PORT=3010
EXPOSE 3010

ENTRYPOINT watchexec -r -w src -- 'zig build run'
